#define Eperm			"permission denied"
#define Eexist			"file does not exist"
#define Edir			"not a directory"
#define Efcall			"bad fcall type"
#define Esrvwrite		"srv write"
#define Eeof			"eof or i/o error on server channel"
#define Ewctlchan		"wctl channel"
#define Econvm2s		"convert error in convM2S"
#define Econvs2m		"convert error in convS2M"
#define Ewrite			"write error in respond"
#define Efirstmsg		"version request not first message"
#define Emsgsz			"version: message size too small"
#define Eunver			"unrecognized 9P version"
#define Ename			"name too long"
#define Enomem			"out of memory"
#define Emouse			"can't find mouse"
#define Ekbd			"can't find keyboard"
#define Escrn			"can't allocate screen"
#define Ewkbd			"can't create keyboard window"
#define Ereattach		"failed to re-attach window"
#define Ereallocscrn		"can't re-allocate screen"
#define Echanalloc		"new: channel alloc failed"
#define Escrtemps		"scrtemps"
#define Escrdraw		"scrdraw"
#define Erealloc		"realloc failed"
#define Emalloc			"malloc failed"
#define Estrdup			"strdup failed"
#define Ebadwr			"bad rectangle in wctl request"
#define Ewalloc			"window allocation failed in wctl request"
#define Eunwctlcmd		"unrecognized wctl command"
#define Emissingwctlparam	"missing or bad wctl parameter"
#define Eunwctlparam		"unrecognized wctl parameter"
#define Ewctlmsg		"extraneous text in wctl message"
#define Eact			"action disallowed when mouse active"
#define Eid			"no such window id"
#define Edeleted		"window deleted"
#define Ewhidden		"window already hidden"
#define Ehide			"hide failed"
#define Enothidden		"window not hidden"
#define Ebadwctlmsg		"invalid wctl message"
#define Eimgname		"image name in use"
#define Enegative		"negative ref count"
#define Eframeselect		"frameselect not right frame"
#define Eunctlmsg		"unknown control message"
#define Eunwindow		"unknown window in closewin"
#define Einuse			"file in use"
#define Etooshort		"buffer too small"
#define Eshort			"short i/o request"
#define Elong			"snarf buffer too long"
#define Eunkid			"unknown id in attach"
#define Ebadrect		"bad rectangle in attach"
#define Ewindow			"cannot make window"
#define Enowindow		"window has no image"
#define Ebadmouse		"bad format on /dev/mouse"
#define Eincref			"incref"
#define Edecref			"decref"
#define Eflushtagalloc		"flushtag in allocate"
#define Eflushtagfree		"flushtag in free"
#define Eref1			"ref 1 in flush"
#define Eoffset			"non-zero offset writing label"
#define Ecursor			"cursor read not implemented"
#define Enoname			"window has no name"
#define Etoplevelscrn		"no top-level screen"
